const $ = (id)=>document.getElementById(id);
const pad = n => String(n).padStart(2,'0');
const todayISO = () => new Date().toISOString().slice(0,10);
const fmtJP = (iso)=>{ const d=new Date(iso+'T00:00:00'); return `${d.getFullYear()}年${d.getMonth()+1}月${d.getDate()}日`; };
const dbName='kanawusagi-pwa-db-v1';
const storeName='files';
const defaultData={appTitle:'カナウサギのんびり日より',mediaTitle:'今日のカナウサギ',year:2026,month:4,maxYear:2027,maxMonth:3,selectedDate:todayISO(),clockStyle:'ピンクもふ',mediaMode:'contain',schedules:[],favorites:[]};
let data=loadData();
let currentMediaUrl=null,currentFavIndex=0,deferredPrompt=null,editingScheduleId=null;
const HOLIDAYS={
 '2026-04-29':'昭和の日','2026-05-03':'憲法記念日','2026-05-04':'みどりの日','2026-05-05':'こどもの日','2026-05-06':'振替休日','2026-07-20':'海の日','2026-08-11':'山の日','2026-09-21':'敬老の日','2026-09-22':'国民の休日','2026-09-23':'秋分の日','2026-10-12':'スポーツの日','2026-11-03':'文化の日','2026-11-23':'勤労感謝の日','2027-01-01':'元日','2027-01-11':'成人の日','2027-02-11':'建国記念の日','2027-02-23':'天皇誕生日','2027-03-20':'春分の日','2027-03-22':'振替休日'
};
const clockThemes={
 'ピンクもふ':{panel:'#fffaf2',face:'#fffdf8',rim:'#f49ab8',hand:'#6b4038',sec:'#e65f8e',text:'#d84f7b'},
 'クラシック':{panel:'#f7f1e8',face:'#fffaf0',rim:'#8b6f47',hand:'#3f3426',sec:'#b64534',text:'#6b4f2a'},
 'ソーダブルー':{panel:'#eef9ff',face:'#ffffff',rim:'#65bfe8',hand:'#24506b',sec:'#2bb5d4',text:'#2d7fa3'},
 'ネオン夜':{panel:'#15172a',face:'#202642',rim:'#9b7cff',hand:'#e9e2ff',sec:'#ff66c4',text:'#9b7cff'}
};
function loadData(){try{return {...defaultData,...JSON.parse(localStorage.getItem('kanawusagiData')||'{}')}}catch(e){return {...defaultData}}}
function save(){localStorage.setItem('kanawusagiData',JSON.stringify(data));}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(dbName,1);r.onupgradeneeded=()=>r.result.createObjectStore(storeName);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function putFile(key,file){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(storeName,'readwrite');tx.objectStore(storeName).put(file,key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error);});}
async function getFile(key){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(storeName,'readonly');const r=tx.objectStore(storeName).get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
async function delFile(key){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(storeName,'readwrite');tx.objectStore(storeName).delete(key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error);});}
function nextMonth(y,m){m++; if(m>12){y++;m=1;} return [y,m];}
function prevMonth(y,m){m--; if(m<1){y--;m=12;} return [y,m];}
function daysInMonth(y,m){return new Date(y,m,0).getDate();}
function iso(y,m,d){return `${y}-${pad(m)}-${pad(d)}`;}
function dateObj(iso){return new Date(iso+'T00:00:00');}
function between(isoDay,s,e){return isoDay>=s && isoDay<=(e||s)}
function schedulesFor(day){return data.schedules.filter(x=>between(day,x.start,x.end||x.start));}
function initTimeOptions(){const opts=[]; for(let h=0;h<24;h++){for(let m=0;m<60;m+=15)opts.push(`${pad(h)}:${pad(m)}`)} ['schStartTime','schEndTime'].forEach(id=>{$(id).innerHTML=opts.map(t=>`<option>${t}</option>`).join('')});}
function init(){
 if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').hidden=false;});
 $('installBtn').onclick=()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;$('installBtn').hidden=true;}};
 initTimeOptions(); bind(); renderAll(); loadMedia(); loadClockImage(); setInterval(drawClock,1000);
}
function bind(){
 $('saveTitleBtn').onclick=()=>{data.appTitle=$('titleInput').value.trim()||defaultData.appTitle;save();renderHeader();};
 $('saveMediaTitleBtn').onclick=()=>{data.mediaTitle=$('mediaTitleInput').value.trim()||'今日のカナウサギ';save();renderMediaTitle();};
 $('mediaPickBtn').onclick=()=>$('mediaFile').click(); $('mediaFile').onchange=handleMedia;
 $('mediaFitBtn').onclick=()=>{data.mediaMode=data.mediaMode==='cover'?'contain':'cover';save();applyMediaFit();};
 $('mediaPauseBtn').onclick=()=>{const v=$('mediaVideo'); if(v.style.display==='none')return; if(v.paused){v.play();$('mediaPauseBtn').textContent='⏸ 一時停止'}else{v.pause();$('mediaPauseBtn').textContent='▶ 再開'}};
 $('mediaClearBtn').onclick=async()=>{await delFile('media');data.mediaFile=null;save();loadMedia();};
 $('prevMonth').onclick=()=>{[data.year,data.month]=prevMonth(data.year,data.month);save();renderCalendar();};
 $('nextMonth').onclick=()=>{let [y,m]=nextMonth(data.year,data.month); if(y>data.maxYear||(y===data.maxYear&&m>data.maxMonth)){data.maxYear=y;data.maxMonth=m;} data.year=y;data.month=m;save();renderCalendar();};
 $('addMonthBtn').onclick=()=>{[data.maxYear,data.maxMonth]=nextMonth(data.maxYear,data.maxMonth);data.year=data.maxYear;data.month=data.maxMonth;save();renderCalendar();};
 $('searchInput').oninput=renderCalendar; $('addScheduleBtn').onclick=()=>openScheduleModal(); $('csvBtn').onclick=exportCSV; $('mailBtn').onclick=mailSchedules;
 $('clockStyle').onchange=()=>{if($('clockStyle').value==='画像取り込み'){$('clockImageFile').click();}else{data.clockStyle=$('clockStyle').value;save();drawClock();}};
 $('clockImageFile').onchange=async e=>{const f=e.target.files[0]; if(!f)return; await putFile('clockImage',f); data.clockStyle='画像時計';save();await loadClockImage();};
 $('addFavBtn').onclick=addFav; $('favSidebarBtn').onclick=()=>openModal('favModal'); $('sunoBtn').onclick=()=>open('https://suno.com/','_blank'); $('xBtn').onclick=()=>open('https://x.com/compose/post','_blank');
 $('backupBtn').onclick=backupJSON; $('restoreBtn').onclick=()=>$('restoreFile').click(); $('restoreFile').onchange=restoreJSON;
 $('saveScheduleBtn').onclick=saveSchedule; $('favOpenBtn').onclick=()=>{const f=data.favorites[currentFavIndex]; if(f)open(f.url,'_blank')}; $('favEditBtn').onclick=()=>editFav(currentFavIndex); $('favDeleteBtn').onclick=()=>deleteFav(currentFavIndex); $('saveFavEditBtn').onclick=saveFavEdit;
 document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));
}
function renderAll(){renderHeader();renderMediaTitle();renderToday();renderCalendar();renderSelected();renderFavs();drawClock();}
function renderHeader(){$('appTitle').textContent=`🐾 ${data.appTitle} 🐾`;$('titleInput').value=data.appTitle;document.title=data.appTitle;}
function renderMediaTitle(){$('mediaTitleLabel').textContent=data.mediaTitle;$('mediaTitleInput').value=data.mediaTitle;}
function renderToday(){const t=todayISO();$('todayText').textContent=fmtJP(t);const items=schedulesFor(t);$('todayFlag').textContent=items.length?'予定あり':'予定なし';}
async function handleMedia(e){const f=e.target.files[0];if(!f)return;await putFile('media',f);data.mediaFile={name:f.name,type:f.type};save();await loadMedia();}
async function loadMedia(){if(currentMediaUrl)URL.revokeObjectURL(currentMediaUrl);currentMediaUrl=null;const img=$('mediaImg'),vid=$('mediaVideo'),empty=$('mediaEmpty');img.style.display=vid.style.display='none';empty.style.display='block';vid.pause();vid.removeAttribute('src');img.removeAttribute('src');let f=await getFile('media'); if(!f){img.src='assets/default_media.jpg';img.onload=()=>{img.style.display='block';empty.style.display='none'};$('mediaHint').textContent='初期画像表示中';applyMediaFit();return;} currentMediaUrl=URL.createObjectURL(f); if(f.type.startsWith('video/')){vid.src=currentMediaUrl;vid.style.display='block';empty.style.display='none';vid.muted=true;vid.loop=true;vid.play().catch(()=>{});$('mediaHint').textContent=`枠内で動画プレビュー中：${f.name}（音はプレイヤーの操作でON）`;}else{img.src=currentMediaUrl;img.style.display='block';empty.style.display='none';$('mediaHint').textContent=`画像表示中：${f.name}`;}applyMediaFit();}
function applyMediaFit(){const stage=$('mediaStage');stage.classList.toggle('fitCover',data.mediaMode==='cover');stage.classList.toggle('fitContain',data.mediaMode!=='cover');$('mediaFitBtn').textContent=data.mediaMode==='cover'?'全体表示':'枠ぴったり';}
async function loadClockImage(){const f=await getFile('clockImage'); if(f&&data.clockStyle==='画像時計'){ $('clockStyle').innerHTML='<option selected>画像時計</option><option>ピンクもふ</option><option>クラシック</option><option>ソーダブルー</option><option>ネオン夜</option><option>画像取り込み</option>'; } else { $('clockStyle').value=clockThemes[data.clockStyle]?data.clockStyle:'ピンクもふ'; } drawClock();}
function drawClock(){const now=new Date();$('digitalClock').textContent=`${pad(now.getHours())}:${pad(now.getMinutes())}:${pad(now.getSeconds())}`;const c=$('clockCanvas'),ctx=c.getContext('2d'),cx=90,cy=90,r=74;ctx.clearRect(0,0,180,180);let th=clockThemes[data.clockStyle]||clockThemes['ピンクもふ'];$('digitalClock').style.color=th.text;ctx.fillStyle=th.panel;ctx.fillRect(0,0,180,180);ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fillStyle=th.face;ctx.fill();ctx.strokeStyle=th.rim;ctx.lineWidth=5;ctx.stroke();for(let i=0;i<60;i++){const a=(i*6-90)*Math.PI/180;const len=i%5===0?10:5;ctx.beginPath();ctx.moveTo(cx+Math.cos(a)*(r-len),cy+Math.sin(a)*(r-len));ctx.lineTo(cx+Math.cos(a)*(r-2),cy+Math.sin(a)*(r-2));ctx.strokeStyle=th.hand;ctx.lineWidth=i%5===0?2:1;ctx.stroke();}ctx.fillStyle=th.hand;ctx.font='bold 15px Yu Gothic UI';ctx.textAlign='center';ctx.textBaseline='middle';for(let n=1;n<=12;n++){const a=(n*30-90)*Math.PI/180;ctx.fillText(n,cx+Math.cos(a)*54,cy+Math.sin(a)*54)}const sec=now.getSeconds(),min=now.getMinutes()+sec/60,h=(now.getHours()%12)+min/60;hand(h*30,38,5,th.hand);hand(min*6,56,4,th.hand);hand(sec*6,65,2,th.sec);ctx.beginPath();ctx.arc(cx,cy,5,0,Math.PI*2);ctx.fillStyle=th.sec;ctx.fill();function hand(deg,len,w,col){const a=(deg-90)*Math.PI/180;ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.cos(a)*len,cy+Math.sin(a)*len);ctx.strokeStyle=col;ctx.lineWidth=w;ctx.lineCap='round';ctx.stroke();}}
function renderCalendar(){const y=data.year,m=data.month;$('calendarTitle').textContent=`${y}年 ${m}月 簡易カレンダー`;const grid=$('calendarGrid');grid.innerHTML='';['月','火','水','木','金','土','日'].forEach((d,i)=>{const e=document.createElement('div');e.className='dow '+(i===5?'sat':i===6?'sun':'');e.textContent=d;grid.appendChild(e)});const first=new Date(y,m-1,1);const startOffset=(first.getDay()+6)%7;const start=new Date(y,m-1,1-startOffset);const q=$('searchInput').value.trim().toLowerCase();for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const isoD=iso(d.getFullYear(),d.getMonth()+1,d.getDate());const dow=(d.getDay()+6)%7;const items=schedulesFor(isoD);const div=document.createElement('div');div.className='day';if(d.getMonth()+1!==m)div.classList.add('out');if(dow===5)div.classList.add('sat');if(dow===6)div.classList.add('sun');if(HOLIDAYS[isoD])div.classList.add('holiday');if(items.length)div.classList.add('has');if(items.some(x=>x.kind.includes('休')||x.flag==='予定なし'))div.classList.add('rest');if(items.some(x=>x.kind==='メモ'))div.classList.add('memo');if(q&&items.some(x=>(x.title+x.memo+x.kind).toLowerCase().includes(q)))div.classList.add('search');if(isoD===data.selectedDate)div.classList.add('selected');if(isoD===todayISO())div.classList.add('today');div.innerHTML=`<span class="num">${d.getDate()}</span>${HOLIDAYS[isoD]?`<span class="holidayName">${HOLIDAYS[isoD]}</span>`:''}${items.length?`<span class="mark">${items.length>1?'●'+items.length:(items.some(x=>x.kind.includes('休'))?'休':'●')}</span>`:''}`;items.slice(0,2).forEach(it=>{if((it.end||it.start)>it.start){const b=document.createElement('div');b.className='bar';b.textContent=(isoD===it.start?'▶ ':'')+(isoD===it.end?' ◀':'');div.appendChild(b)}});if(isoD===todayISO()){const t=document.createElement('span');t.className='todayLabel';t.textContent='今日';div.appendChild(t)}div.onclick=()=>{data.selectedDate=isoD; if(d.getMonth()+1!==data.month){data.year=d.getFullYear();data.month=d.getMonth()+1;}save();renderCalendar();renderSelected();};div.ondblclick=()=>openScheduleModal();grid.appendChild(div)}}
function renderSelected(){const d=data.selectedDate;$('selectedTitle').textContent=`選択日：${fmtJP(d)}`;const list=$('selectedList');const items=schedulesFor(d);if(!items.length){list.innerHTML='<p>予定なし：やーい暇人</p>';return;}list.innerHTML=items.map(it=>`<div class="scheduleItem"><b>${escapeHTML(it.title||'(無題)')}</b> <small>${it.startTime||''}${it.endTime?'〜'+it.endTime:''}</small><br><span>${escapeHTML(it.kind)} / ${escapeHTML(it.priority)} / ${escapeHTML(it.state)}</span><br><small>${escapeHTML(it.memo)}</small></div>`).join('');}
function openScheduleModal(){editingScheduleId=null;$('scheduleModalTitle').textContent='予定入力';const d=data.selectedDate;$('schStart').value=d;$('schEnd').value=d;$('schStartTime').value='09:00';$('schEndTime').value='10:00';$('schTitle').value='';$('schMemo').value='';$('schKind').value='日常';$('schFlag').value='予定あり';$('schPriority').value='中';$('schState').value='未着手';renderScheduleEditList();openModal('scheduleModal');}
function saveSchedule(){const rec={id:editingScheduleId||crypto.randomUUID(),start:$('schStart').value,end:$('schEnd').value||$('schStart').value,startTime:$('schStartTime').value,endTime:$('schEndTime').value,title:$('schTitle').value.trim(),memo:$('schMemo').value.trim(),kind:$('schKind').value,flag:$('schFlag').value,priority:$('schPriority').value,state:$('schState').value};if(!rec.start||!rec.end){alert('日付を入れてください');return;} if(rec.end<rec.start){alert('終了日は開始日以降にしてください');return;}const idx=data.schedules.findIndex(x=>x.id===rec.id);if(idx>=0)data.schedules[idx]=rec;else data.schedules.push(rec);editingScheduleId=null;save();renderAll();renderScheduleEditList();}
function renderScheduleEditList(){const box=$('scheduleEditList');const items=data.schedules.filter(x=>between(data.selectedDate,x.start,x.end||x.start));if(!items.length){box.innerHTML='<p>この日の登録済み予定はありません。</p>';return;}box.innerHTML='';items.forEach(it=>{const row=document.createElement('div');row.className='editRow';row.innerHTML=`<div><b>${escapeHTML(it.title||'(無題)')}</b><br><small>${it.start} ${it.startTime||''}〜${it.end||it.start} ${it.endTime||''}</small></div>`;const eb=document.createElement('button');eb.textContent='編集';eb.onclick=()=>loadScheduleForEdit(it.id);const db=document.createElement('button');db.textContent='削除';db.className='dangerLight';db.onclick=()=>deleteSchedule(it.id);row.append(eb,db);box.appendChild(row);});}
function loadScheduleForEdit(id){const it=data.schedules.find(x=>x.id===id);if(!it)return;editingScheduleId=id;$('scheduleModalTitle').textContent='予定編集';$('schStart').value=it.start;$('schEnd').value=it.end||it.start;$('schStartTime').value=it.startTime||'09:00';$('schEndTime').value=it.endTime||'10:00';$('schTitle').value=it.title||'';$('schMemo').value=it.memo||'';$('schKind').value=it.kind||'日常';$('schFlag').value=it.flag||'予定あり';$('schPriority').value=it.priority||'中';$('schState').value=it.state||'未着手';}
function deleteSchedule(id){if(!confirm('この予定を削除しますか？'))return;data.schedules=data.schedules.filter(x=>x.id!==id);save();renderAll();renderScheduleEditList();}
function addFav(){const name=$('favName').value.trim(),url=$('favUrl').value.trim(),memo=$('favMemo').value.trim();if(!name||!url){alert('名前とURLを入れてください');return;}data.favorites.push({id:crypto.randomUUID(),name,url,memo});$('favName').value=$('favUrl').value=$('favMemo').value='';save();renderFavs();}
function renderFavs(){const box=$('favList');if(!data.favorites.length){box.innerHTML='<p>まだお気に入りがありません。</p>';return;}box.innerHTML='';data.favorites.forEach((f,i)=>{const row=document.createElement('div');row.className='favRow';row.innerHTML=`<div class="favInfo"><div class="favName">${escapeHTML(f.name)}</div><div class="favMemo">${escapeHTML(f.memo||'')}</div></div>`;row.querySelector('.favInfo').onclick=()=>open(f.url,'_blank');const eb=document.createElement('button');eb.textContent='編集';eb.onclick=()=>editFav(i);const db=document.createElement('button');db.textContent='削除';db.className='dangerLight';db.onclick=()=>deleteFav(i);row.append(eb,db);box.appendChild(row)});renderFavSidebar();}
function renderFavSidebar(){const box=$('favSideList');if(!box)return;box.innerHTML='';data.favorites.forEach((f,i)=>{const div=document.createElement('div');div.className='favSideItem '+(i===currentFavIndex?'active':'');div.innerHTML=`<b>${escapeHTML(f.name)}</b><br><small>${escapeHTML(f.memo||'')}</small>`;div.onclick=()=>{currentFavIndex=i;renderFavSidebar();renderFavDetail();};box.appendChild(div)});renderFavDetail();}
function renderFavDetail(){const f=data.favorites[currentFavIndex];$('favDetailName').textContent=f?f.name:'お気に入りを選択';$('favDetailMemo').textContent=f?f.memo:'';$('favDetailUrl').textContent=f?f.url:'';}
function editFav(i){const f=data.favorites[i];if(!f)return;currentFavIndex=i;$('editFavName').value=f.name;$('editFavUrl').value=f.url;$('editFavMemo').value=f.memo||'';openModal('favEditModal');}
function saveFavEdit(){const f=data.favorites[currentFavIndex];if(!f)return;f.name=$('editFavName').value.trim();f.url=$('editFavUrl').value.trim();f.memo=$('editFavMemo').value.trim();save();closeModal('favEditModal');renderFavs();}
function deleteFav(i){if(!data.favorites[i])return;if(!confirm('このお気に入りを削除しますか？'))return;data.favorites.splice(i,1);currentFavIndex=0;save();renderFavs();}
function exportCSV(){const rows=[['開始日','終了日','開始時刻','終了時刻','年','月','予定有無','種別','優先度','状態','予定内容','メモ']];data.schedules.forEach(it=>{const d=dateObj(it.start);rows.push([it.start,it.end||it.start,it.startTime||'',it.endTime||'',d.getFullYear(),d.getMonth()+1,it.flag,it.kind,it.priority,it.state,it.title,it.memo])});download('\ufeff'+rows.map(r=>r.map(csvCell).join(',')).join('\n'),'kanawusagi_schedule.csv','text/csv;charset=utf-8');}
function mailSchedules(){const items=schedulesFor(data.selectedDate);const body=items.length?items.map(it=>`・${it.title} ${it.startTime||''}${it.endTime?'〜'+it.endTime:''}\n  ${it.memo||''}`).join('\n'):'予定なし';location.href=`mailto:?subject=${encodeURIComponent('カナウサギ予定 '+fmtJP(data.selectedDate))}&body=${encodeURIComponent(body)}`;}
function backupJSON(){download(JSON.stringify(data,null,2),'kanawusagi_backup.json','application/json');}
function restoreJSON(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{data={...defaultData,...JSON.parse(r.result)};save();renderAll();alert('読み込みました');}catch(err){alert('JSONを読み込めませんでした')}};r.readAsText(f,'utf-8');}
function download(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function csvCell(v){v=String(v??'');return /[",\n]/.test(v)?`"${v.replaceAll('"','""')}"`:v;}
function openModal(id){if(id==='favModal')renderFavSidebar();$(id).hidden=false;}function closeModal(id){$(id).hidden=true;}
function escapeHTML(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
init();
